# Generated by Django 4.1.5 on 2023-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('buget', models.IntegerField(default=0)),
                ('movie_release_location', models.CharField(max_length=200)),
                ('release_date', models.DateField(max_length=200)),
                ('actors', models.ManyToManyField(to='movieapp.actors')),
            ],
        ),
    ]
